spring:
  datasource:
    password: PNSJkxXvVNDAhePMuExTBuRR
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:6603/serverdb
    username: servermanager
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true